bluelog/blueprints/admin.py
from flask import Blueprint, redirect, url_for, render_template
from flask_login import current_user
from sqlalchemy import and_

from bluelog import User, db
from bluelog.models import Post, Comment, UnreadMessage

admin_bp = Blueprint('admin', __name__)


@admin_bp.route('/test')
def login():
    return "this is admin's test"


@admin_bp.route('/index')
def index():
    if not current_user.is_authenticated:
        return redirect(url_for('auth.login'))
    else:
        recentPosts = Post.query.filter(Post.user_id == current_user.id).order_by(Post.postTime.desc()).limit(5)
        recentComments = Comment.query.filter(Comment.user_id == current_user.id) \
            .order_by(Comment.timestamp.desc()).limit(5)
        return render_template('admin/index.html', posts=recentPosts, comments=recentComments)


@admin_bp.route('/posts')
def managePosts():
    if not current_user.is_authenticated:
        return redirect(url_for('blog.index'))
    else:
        allPosts = Post.query.filter(Post.user_id == current_user.id).order_by(Post.postTime.desc()).all()
        return render_template('admin/managePosts.html', posts=allPosts)


@admin_bp.route('/comments')
def manageComments():
    if not current_user.is_authenticated:
        return redirect(url_for('blog.index'))
    else:
        allComments = Comment.query.filter(Comment.user_id == current_user.id).order_by(Comment.timestamp.desc()).all()
        return render_template('admin/manageComments.html', comments=allComments)


@admin_bp.route('/deletePost/<int:post_id>')
def deletePost(post_id):
    post = Post.query.get(post_id)
    if post:
        posterId = post.user_id
        if current_user.is_authenticated and current_user.id == posterId:
            for comment in post.comments:
                unreadMessages = UnreadMessage.query.filter(UnreadMessage.comment_id == comment.id).all()
                for unreadMessage in unreadMessages:
                    db.session.delete(unreadMessage)
                db.session.delete(comment)
            db.session.delete(post)
            db.session.commit()
            return redirect(url_for('admin.managePosts'))
        else:
            return redirect(url_for('blog.index'))
    else:
        return redirect(url_for('blog.index'))


@admin_bp.route('/deleteComment/<int:comment_id>')
def deleteComment(comment_id):
    comment = Comment.query.get(comment_id)
    if comment:
        commenterId = comment.user_id
        if current_user.is_authenticated and current_user.id == commenterId:
            unreadMessages = UnreadMessage.query.filter(UnreadMessage.comment_id == comment.id).all()
            for unreadMessage in unreadMessages:
                db.session.delete(unreadMessage)
            db.session.delete(comment)
            db.session.commit()
            return redirect(url_for('admin.manageComments'))
    return redirect(url_for('blog.index'))


@admin_bp.route('/unreadMessages')
def manageUnreadMessages():
    if not current_user.is_authenticated:
        return redirect(url_for('blog.index'))
    else:
        unreadMessages = UnreadMessage.query.filter(and_(UnreadMessage.user_id == current_user.id,
                                                         UnreadMessage.haveRead == 0)).all()
        readMessages = UnreadMessage.query.filter(and_(UnreadMessage.user_id == current_user.id,
                                                       UnreadMessage.haveRead == 1)).all()
        unreadMessages = Comment.query.filter(Comment.id.in_([unreadMessage.comment_id for unreadMessage in unreadMessages])).order_by(Comment.timestamp.desc()).all()
        readMessages = Comment.query.filter(Comment.id.in_([readMessage.comment_id for readMessage in readMessages])).order_by(Comment.timestamp.desc()).all()
        return render_template('admin/manageUnreadMessage.html', comments=unreadMessages, readComments=readMessages)


@admin_bp.route('/readAll')
def readAll():
    if not current_user.is_authenticated:
        return redirect(url_for('blog.index'))
    else:
        unreadMessages = UnreadMessage.query.filter(and_(UnreadMessage.user_id == current_user.id,
                                                         UnreadMessage.haveRead == 0)).all()
        for unreadMessage in unreadMessages:
            unreadMessage.haveRead = True
        db.session.commit()
        return redirect(url_for('admin.manageUnreadMessages'))

bluelog/blueprints/auth.py
from flask import Blueprint, render_template, url_for, redirect, session, flash
from flask_login import current_user, login_user, login_required, logout_user

from bluelog.models import User
from bluelog.forms import LoginForm, RegisterForm

from bluelog.extensions import mail, db
from bluelog.functions import redirect_back

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('blog.index'))

    loginForm = LoginForm()
    if loginForm.validate_on_submit():
        email = loginForm.email.data
        password = loginForm.password.data
        remember = loginForm.remember.data
        user = User.query.filter(User.email == email).first()
        if user:
            if email == user.email and password == user.password:
                login_user(user, remember)
                return redirect(url_for('blog.index'))

    return render_template('auth/login.html', form=loginForm)


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect_back()


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    registerForm = RegisterForm()
    if registerForm.validate_on_submit():
        email = registerForm.emailAddress.data
        if not User.query.filter(User.email == email).first():
            user = User(email=email, password=registerForm.password.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('auth.login'))
        else:
            flash("This Email has already been used")

    return render_template('auth/register.html', registerForm=registerForm)

bluelog/blueprints/blog.py
from datetime import datetime

from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_login import current_user
from sqlalchemy import and_, or_
from jieba import lcut_for_search

from bluelog import db
from bluelog.extensions import fake
from bluelog.forms import PostForm, ReplyForm, SearchForm
from bluelog.models import Post, Comment, User, FakeName, UnreadMessage

blog_bp = Blueprint('blog', __name__)


@blog_bp.route('/', methods=['GET', 'POST'])
def hello():
    if current_user.is_authenticated:
        return redirect(url_for('blog.index'))
    return render_template('blog/hello.html')


@blog_bp.route('/index', methods=['GET', 'POST'])
def index():
    form = PostForm()
    if form.validate_on_submit():
        if current_user.is_authenticated:
            name = form.name.data
            title = form.title.data
            body = form.body.data
            post = Post(body=body, title=title, name=name)
            db.session.add(post)
            user = User.query.filter_by(id=current_user.id).first()
            post.user = user
            fakeName = FakeName(post_id=post.id, user_id=user.id, name=name)
            db.session.add(fakeName)
            db.session.commit()
            return redirect(url_for('blog.index'))
        else:
            flash('Please Login to Post Message')

    form.name.data = fake.name()
    posts = Post.query.order_by(Post.timestamp.desc()).all()
    return render_template('blog/index.html',
                           form=form,
                           posts=posts)


@blog_bp.route('/post/<int:post_id>', methods=['GET', 'POST'])
def replyPage(post_id):

    replyName = request.args.get('replyName')
    if replyName:
        replyForm = ReplyForm(toName=replyName)
    else:
        replyForm = ReplyForm()

    fakesNames = FakeName.query.filter_by(post_id=post_id).all()
    replyForm.toName.choices = [(fakeName.name, fakeName.name) for fakeName in fakesNames]
    post = Post.query.get(post_id)
    post.clickNum += 1
    comments = post.comments
    db.session.commit()
    if replyForm.validate_on_submit():
        if current_user.is_authenticated:
            name = replyForm.name.data
            body = replyForm.body.data
            toName = replyForm.toName.data
            if toName == post.name:
                toName = None
            comment = Comment(body=body, name=name, replyTo=toName, commentFloor=post.commentNum + 1)
            user = User.query.get(current_user.id)
            post.timestamp = datetime.now()
            comment.user = user
            comment.post = post
            fakeName = FakeName.query.filter(and_(FakeName.post_id == post_id, FakeName.user_id == user.id)).first()
            post.commentNum += 1
            if not fakeName:
                fn = FakeName(post_id=post.id, user_id=user.id, name=name)
                db.session.add(fn)
            db.session.commit()

            # toName is None意味着消息是回复给楼主的
            # name == post.name意味着消息是楼主发出的
            if toName is None and name != post.name:
                # 用户回复给楼主
                unReadMessage = UnreadMessage(comment_id=comment.id, user_id=post.user_id)
                db.session.add(unReadMessage)
                db.session.commit()
            elif toName is None and name == post.name:
                # 楼主回复楼主
                pass
            elif toName is not None and name != post.name:
                # 用户回复用户
                unReadMessage0 = UnreadMessage(comment_id=comment.id, user_id=post.user_id)
                toNameId = FakeName.query.filter(
                    and_(FakeName.name == toName, FakeName.post_id == post.id)).first().user_id
                unReadMessage1 = UnreadMessage(comment_id=comment.id, user_id=toNameId)
                db.session.add(unReadMessage0)
                db.session.add(unReadMessage1)
                db.session.commit()
            elif name == post.name and toName is not None:
                # 楼主回复用户
                toNameId = FakeName.query.filter(
                    and_(FakeName.name == toName, FakeName.post_id == post.id)).first().user_id
                unReadMessage = UnreadMessage(comment_id=comment.id, user_id=toNameId)
                db.session.add(unReadMessage)
                db.session.commit()

            return redirect(url_for('blog.replyPage', post_id=post_id))
        else:
            flash('Please Login to Reply Post')
    if current_user.is_authenticated:
        user = User.query.get(current_user.id)
        fakeName = FakeName.query.filter(and_(FakeName.post_id == post_id, FakeName.user_id == user.id)).first()
        if fakeName:
            replyForm.name.data = fakeName.name
        else:
            nameTemp = fake.name()
            while nameTemp in [fakeName.name for fakeName in fakesNames]:
                nameTemp = fake.name()
            replyForm.name.data = nameTemp
    else:
        nameTemp = fake.name()
        while nameTemp in [fakeName.name for fakeName in fakesNames]:
            nameTemp = fake.name()
        replyForm.name.data = nameTemp
    return render_template('blog/reply.html',
                           comments=comments,
                           form=replyForm,
                           post=post)


@blog_bp.route('/search', methods=['GET', 'POST'])
def searchMessage():
    searchForm = SearchForm()
    if searchForm.validate_on_submit():
        searchRule = searchForm.body.data
        searchList = lcut_for_search(searchRule)
        rules = ""
        for rule in searchList:
            rules += rule + "|"
        rules = rules.rstrip("|")
        searchedPost = Post.query.filter(or_(Post.body.op('regexp')(rules),
                                             Post.title.op('regexp')(rules)))
        searchComment = Comment.query.filter(Comment.body.op('regexp')(rules))

        return render_template('blog/search.html',
                               searchPostNumber=searchedPost.count(),
                               searchCommentNumber=searchComment.count(),
                               posts=searchedPost,
                               comments=searchComment)

    return redirect(url_for('blog.index'))


@blog_bp.route('/replyFromComment/<int:comment_id>')
def replyFromComment(comment_id):
    comment = Comment.query.get(comment_id)
    return redirect(url_for('blog.replyPage', post_id=comment.post_id, replyName=comment.name) + '#comment-form')

bluelog/templates/base.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>Say Hello</title>
    <link rel="icon" href="{{ url_for('static', filename='bitbug_favicon.ico') }}" type="image/x-icon">
    <link rel="stylesheet" href="{{ url_for('static', filename='/bootstrap-3.4.1-dist/css/bootstrap.min.css') }}">
    <!-- Bootstrap -->
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
          integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

</head>
<body>
{% block nav %}
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('blog.index') }}">Say Hello</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('admin.index') }}">Account</a></li>
                </ul>
                <form class="navbar-form navbar-left" method="post" action="{{ url_for('blog.searchMessage') }}">
                    {{ searchForm.csrf_token }}
                    <div class="form-group">
                        {{ searchForm.body(class="form-control", placeholder="Search") }}
                    </div>
                    {{ searchForm.submit(type="submit", class="btn btn-default") }}
                </form>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                        <li role="presentation"><a href="{{ url_for('admin.manageUnreadMessages') }}">Messages <span
                                class="badge">{{ unreadMessageNum }}</span></a></li>
                        <li><a href="{{ url_for('auth.logout', next=request.full_path) }}">Logout</a></li>
                    {% else %}
                        <li><a href="{{ url_for('auth.login', next=request.full_path) }}">Login</a></li>
                        <li><a href="{{ url_for('auth.register', next=request.full_path) }}">Register</a></li>
                    {% endif %}
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
{% endblock nav %}
{% block title %}{% endblock title %}
{% block content %}{% endblock content %}
<!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
<script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"
        integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ"
        crossorigin="anonymous"></script>
<!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
        integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd"
        crossorigin="anonymous"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/bootstrap-select.min.js"></script>
</body>
</html>

bluelog/templates/macros.html
{% macro show_flash() %}
    {% for message in get_flashed_messages() %}
        <div class="alert alert-info alert-dismissible" role="alert" style="margin:0 auto; width:90%">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span class="sr-only">Error:</span>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                    aria-hidden="true">&times;</span></button>
            <a href="{{ url_for('auth.login') }}" class="alert-link" style="font-weight: lighter">{{ message }}</a>
        </div>
    {% endfor %}
{% endmacro %}

{% macro show_footer() %}
    <footer class="text-center" style="margin-top: 20px;">
        <small> &copy; 2021 <a href="https://github.com/luyueti111" title="Written by Grey Li">Yueti Lu</a> /
            <a href="https://github.com/luyueti111/Bluelog" title="Fork me on GitHub">GitHub</a> /
            <a href="{{ url_for('blog.hello') }}" title="A HelloFlask project">Say Hello</a>
        </small>
    </footer>
{% endmacro %}

{% macro show_post_in_index(post) %}
    <a class="list-group-item" href="{{ url_for('blog.replyPage', post_id=post.id) }}">
        <span class="badge">{{ post.commentNum }}</span>
        <h4 class="list-group-item-heading">{{ post.title }}</h4>
        <p class="list-group-item-text"
           style="width: 100%; word-break: break-all; word-wrap: break-word">{{ post.body }}</p>
        <small style="right: 0">
            最后回复:{{ post.timestamp.strftime('%Y/%m/%d %H:%M') }}&nbsp;&nbsp;
        </small>
        <small class="pull-right">点击量:{{ post.clickNum }}&nbsp;&nbsp;</small>
    </a>
{% endmacro %}

{% macro show_post_in_admin(post) %}
    <li class="list-group-item">
        <a href="{{ url_for('blog.replyPage', post_id=post.id) }}" style="color: inherit; text-decoration: none;">

            <h4 class="list-group-item-heading">{{ post.title }}<span
                    class="badge pull-right">{{ post.commentNum }}</span></h4>
            <p class="list-group-item-text"
               style="width: 100%; word-break: break-all; word-wrap: break-word">{{ post.body }}</p>
            <small style="right: 0">
                最后回复:{{ post.timestamp.strftime('%Y/%m/%d %H:%M') }}&nbsp;&nbsp;
            </small>
            <small>点击量:{{ post.clickNum }}&nbsp;&nbsp;</small>
        </a>
        <a href="{{ url_for('admin.deletePost', post_id=post.id) }}"
           class="btn btn-link pull-right btn-xs"
           onclick="return confirm('Are you Sure?')">Delete</a>
    </li>
{% endmacro %}

{% macro show_comment_in_post(comment) %}
    {% set post = comment.post %}
    <li class="list-group-item">
        {% if comment.name == post.name %}
            <h4 class="list-group-item-heading text-info">{{ comment.name }}<small
                    class="pull-right">&nbsp;#{{ comment.commentFloor }}</small>
            </h4>
        {% else %}
            <h4 class="list-group-item-heading">{{ comment.name }}<small
                    class="pull-right">&nbsp;#{{ comment.commentFloor }}</small>
            </h4>
        {% endif %}
        {% if comment.replyTo is not none %}
            <h5><small>Reply to&nbsp;&nbsp;</small>{{ comment.replyTo }}</h5>
        {% endif %}
        <p class="list-group-item-text"
           style="width: 100%; word-break: break-all; word-wrap: break-word; font-size: medium">{{ comment.body }}</p>
        <small>
            {{ comment.timestamp.strftime('%Y/%m/%d %H:%M') }}
        </small>
        <a class="btn  btn-link btn-xs pull-right" href="{{ url_for('blog.replyFromComment', comment_id=comment.id) }}">Reply</a>
    </li>
{% endmacro %}


{% macro show_comment_in_href(comment) %}
    {% set post = comment.post %}
    <li class="list-group-item">
        <a href="{{ url_for('blog.replyPage', post_id=comment.post_id) }}"
           style="color: inherit; text-decoration: none;">
            {% if comment.name == post.name %}
                <h4 class="list-group-item-heading text-info">{{ comment.name }}<small
                        class="pull-right">&nbsp;#{{ comment.commentFloor }}</small>
                </h4>
            {% else %}
                <h4 class="list-group-item-heading">{{ comment.name }}<small
                        class="pull-right">&nbsp;#{{ comment.commentFloor }}</small>
                </h4>
            {% endif %}

            {% if comment.replyTo is not none %}
                <h5><small>Reply to&nbsp;&nbsp;</small>{{ comment.replyTo }}</h5>
            {% endif %}
            <p class="list-group-item-text"
               style="width: 100%; word-break: break-all; word-wrap: break-word; font-size: medium">{{ comment.body }}</p>
            <small>
                {{ comment.timestamp.strftime('%Y/%m/%d %H:%M') }}
            </small>
            <a class="btn btn-link btn-xs pull-right"
               href="{{ url_for('blog.replyFromComment', comment_id=comment.id) }}">Reply</a>
        </a>
    </li>
{% endmacro %}

{% macro show_comment_in_admin(comment) %}
    {% set post = comment.post %}
    <li class="list-group-item">
        <a href="{{ url_for('blog.replyPage', post_id=comment.post_id) }}"
           style="color: inherit; text-decoration: none;">
            {% if comment.name == post.name %}
                <h4 class="list-group-item-heading text-info">{{ comment.name }}<small class="pull-right">&nbsp;&nbsp;&nbsp;#{{ comment.commentFloor }}</small>
                </h4>
            {% else %}
                <h4 class="list-group-item-heading">{{ comment.name }}<small
                        class="pull-right">&nbsp;&nbsp;&nbsp;#{{ comment.commentFloor }}</small>
                </h4>
            {% endif %}

            {% if comment.replyTo is not none %}
                <h5><small>Reply to&nbsp;&nbsp;</small>{{ comment.replyTo }}</h5>
            {% endif %}
            <p class="list-group-item-text"
               style="width: 100%; word-break: break-all; word-wrap: break-word; font-size: medium">{{ comment.body }}</p>
            <small>
                {{ comment.timestamp.strftime('%Y/%m/%d %H:%M') }}
            </small>
        </a>
        <a href="{{ url_for('admin.deleteComment', comment_id=comment.id) }}"
           class="btn btn-link pull-right btn-xs"
           onclick="return confirm('Are you Sure?')">Delete</a>
    </li>
{% endmacro %}


{% macro show_errors(errors) %}
    {% for error in errors %}
        <div class="alert alert-danger alert-dismissible" role="alert" style="width:90%; margin: 3px auto 0;">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                    aria-hidden="true">&times;</span></button>
            {{ error }}
        </div>
    {% endfor %}
{% endmacro %}